### ISSUE TITLE
Search song features 

### ISSUE THREAD

**Issue by iamsonukushwaha** [iamsonukushwaha/tarana#106]

**Comment by shyam-2002** [comment]
Hey ! I would like to work on this issue. Can you please assign it to me.

**Comment by Shizzzzzzz7** [comment]
I would like to work on this issue please assign it to me

**Comment by flyingsonu122** [comment]
@shyam-2002 @Shizzzzzzz7 kindly update on your progress, else will remove assignment

**Comment by Bharadwajshivam28** [comment]
@flyingsonu122 Hello sir I want to work on this please assign me not under any event I just want to fix it

**Comment by flyingsonu122** [comment]
> @flyingsonu122 Hello sir I want to work on this please assign me not under any event I just want to fix it

Glad to hear, go ahead. Assigned to you
