### ISSUE TITLE
implement more methods to signup and login

### ISSUE THREAD

**Issue by iamsonukushwaha** [iamsonukushwaha/tarana#115]
login signup is already there with email& password and google, we need to implement more methods like facebook, twitter, github, others  and sending a login link to email  to signup and login

**Comment by Yogeshlodhi** [comment]
@flyingsonu122 Please assign this to me ....I can add more options and do some styling as well.
Also please give some examples of What other methods do you expect to see?

**Comment by Pjha72** [comment]
Pls assign to me

**Comment by Pjha72** [comment]
I can add Facebook and twiiter

**Comment by Pjha72** [comment]
@flyingsonu122 pls assign to me

**Comment by flyingsonu122** [comment]
@Pjha72 assigned

**Comment by Bharadwajshivam28** [comment]
@flyingsonu122 Hello sir i can make more options in the box

**Comment by Bharadwajshivam28** [comment]
thanks
