### ISSUE TITLE
Fetch songs using API

### ISSUE THREAD

**Issue by iamsonukushwaha** [iamsonukushwaha/tarana#97]
kindly use any of these APIs to fetch songs, and show on the website

![image](https://user-images.githubusercontent.com/51280276/205851277-5cbfb2e1-4f31-4b26-ab1b-136c6633eb6c.png)

**Comment by raunak-mishra** [comment]
@flyingsonu122 I'd like to take this up. Kindly assign it

**Comment by flyingsonu122** [comment]
> @flyingsonu122 I'd like to take this up. Kindly assign it

@raunak-mishra assigned to you

**Comment by raunak-mishra** [comment]
@flyingsonu122 thank you

**Comment by Abhijeet-2003** [comment]
I've worked on a similar issue previously @flyingsonu122. Please assign this to me.

**Comment by Abhijeet-2003** [comment]
Should I just fork the "codepeak" branch for my issue ? @flyingsonu122

**Comment by flyingsonu122** [comment]
> Should I just fork the "codepeak" branch for my issue ? @flyingsonu122 

yes @Abhijeet-2003

**Comment by Abhijeet-2003** [comment]
I've created a pr for this issue @flyingsonu122. Please review and merge.

**Comment by prithidevghosh** [comment]
@flyingsonu122 Hey , can i work on this ?

**Comment by flyingsonu122** [comment]
Yes please. Thank you

**Comment by ABHILASHREDDY-123** [comment]
assign this to me pls. I have experience on this a lot.

**Comment by flyingsonu122** [comment]
@ABHILASHREDDY-123 assigned to you. Thanks
