### ISSUE TITLE
Add more songs 

### ISSUE THREAD

**Issue by iamsonukushwaha** [iamsonukushwaha/tarana#99]
1. Add songs in music folder with proper name 

1. Add songs related image in img folder with proper name

1. Then edit songs.json file with details as provided format 

create PR in https://github.com/flyingsonu122/tarana/tree/99-add-more-songs branch only

**Note** everyone is encouraged to add songs

**Comment by Shivam-jainn** [comment]
What and how are we planning to add more songs here?

**Comment by flyingsonu122** [comment]
> What and how are we planning to add more songs here?

Check description

**Comment by SandeepUrankar** [comment]
Assign me.

**Comment by Pjha72** [comment]
Assign me.

**Comment by SandeepUrankar** [comment]
There isn't any language constraint, right?
Can add any languages?

**Comment by flyingsonu122** [comment]
which language you want to add?

**Comment by SandeepUrankar** [comment]
English and Hindi?

**Comment by flyingsonu122** [comment]
on hindi as of now
